name: Test start, release and image push

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write
  id-token: write

jobs:
  testrun:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Configure Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Test script run
        run: bun ci:test

  build-and-release:
    runs-on: ubuntu-latest
    needs: [testrun]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun i --frozen-lockfile

      - name: Install RAR
        run: |
          sudo apt-get update
          sudo apt-get install -y rar

      - name: Compile Windows executable and pack it with dependencies
        run: |
          bun "release:win-x64"

          mkdir -p ./dist/acsd-assistant-win/database

          cp -r ./database/migrations ./dist/acsd-assistant-win/database/migrations

          cp .env.example ./dist/acsd-assistant-win/.env

          cd ./dist
          zip -r acsd-assistant-${{ github.ref_name }}-win-x64.zip ./acsd-assistant-win
          rar a -r acsd-assistant-${{ github.ref_name }}-win-x64.rar ./acsd-assistant-win

      - name: Compile Linux binary and pack it with dependencies
        run: |
          bun "release:linux-x64"

          mkdir -p ./dist/acsd-assistant-linux/database

          cp -r ./database/migrations ./dist/acsd-assistant-linux/database/migrations

          cp .env.example ./dist/acsd-assistant-linux/.env

          cd ./dist
          zip -r acsd-assistant-${{ github.ref_name }}-linux-x64.zip ./acsd-assistant-linux
          rar a -r acsd-assistant-${{ github.ref_name }}-linux-x64.rar ./acsd-assistant-linux

      - name: Create GitHub release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            ./dist/acsd-assistant-${{ github.ref_name }}-win-x64.zip
            ./dist/acsd-assistant-${{ github.ref_name }}-win-x64.rar
            ./dist/acsd-assistant-${{ github.ref_name }}-linux-x64.zip
            ./dist/acsd-assistant-${{ github.ref_name }}-linux-x64.rar
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  docker-build-push:
    runs-on: ubuntu-latest
    needs: [testrun]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Login to GitHub Container Registry (GHCR)
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v6
        with:
          images: ghcr.io/${{ github.repository }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
